# Generated by Django 5.2.3 on 2026-04-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_memberprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('general_fitness', 'General Fitness'), ('strength_training', 'Strength Training'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('body_toning', 'Body Toning')], max_length=50),
        ),
    ]
